#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
#autorandr --skip-options crtc -c
python3 ~/.config/bspwm/monitors3.py
python3 ~/.config/bspwm/monitors2.py

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config window_gap          12
bspc config border_width 4
bspc config normal_border_color '#4C566A'
bspc config active_border_color '#4C566A'
bspc config focused_border_color '#D8DEE9'


#xcursor fix
xsetroot -cursor_name left_ptr &

#autostart

~/.config/polybar/launch.sh &
picom --experimental-backends &
nitrogen --restore &
~/.config/dunst/reload.sh


#sudo $HOME/.xinitrc
