#!/usr/bin/env bash
notify-send "Getting list of available Wi-Fi networks..."

nmcli d wifi rescan

# Get a list of available wifi connections and morph it into a nice-looking list
wifi_command=$(nmcli --fields "SECURITY,BSSID,SSID,BARS,ACTIVE" device wifi list)
wifi_list=$(printf "$wifi_command" | uniq | sed 1d | grep -v yes | sed "1 i$(printf "$wifi_command" | grep yes) \\" | sed 's/  */ /g' | sed -E "s/WPA*.?\S/ /g" | sed "s/^--/ /g" | sed "s/  //g" | sed "/--/d" | sed "s/ no//g" | sed "s/ yes/ */g" | awk '{$2="";$0=$0} NF=NF' | column -t)

#printf "$(printf "$wifi_command" | sed 1d | grep -v yes | sed "1 i$(printf "$wifi_command" | grep yes) \\")" 


connected=$(nmcli -fields WIFI g)
if [[ "$connected" =~ "enabled" ]]; then
	toggle="睊  Disable Wi-Fi"
elif [[ "$connected" =~ "disabled" ]]; then
	toggle="直  Enable Wi-Fi"
fi

# Use rofi to select wifi network
chosen_network=$(echo -e "$toggle\n$wifi_list" | uniq -u | rofi -dmenu -i -selected-row 1 -theme-str '@import "~/.config/rofi/themes/apps.rasi"' -p "Wi-Fi SSID" )
# Get name of connection
#chosen_id=$(echo "${chosen_network:3}" | xargs | awk '{print $1}')
chosen_network_name=$(echo "${chosen_network:3:-1}" | awk '{$NF="";print}')
chosen_id=$(printf "$wifi_command" | grep "$chosen_network_name" | awk '{print $3}')
echo $chosen_id
if [ "$chosen_network" = "" ]; then
	exit
elif [ "$chosen_network" = "直  Enable Wi-Fi" ]; then
	nmcli radio wifi on
elif [ "$chosen_network" = "睊  Disable Wi-Fi" ]; then
	nmcli radio wifi off
else
	# Message to show when connection is activated successfully
	success_message="You are now connected to the Wi-Fi network \"${chosen_network_name:0:-1}\"."
	# Get saved connections
	saved_connections=$(nmcli -g NAME connection)
    [[ $(echo "$saved_connections" | grep "${chosen_network_name:0:-1}") = "${chosen_network_name:0:-1}" ]] && echo hi
	if [[ $(echo "$saved_connections" | grep -w "${chosen_network_name:0:-1}") = "${chosen_network_name:0:-1}" ]]; then
		nmcli connection up id "${chosen_network_name:0:-1}" | grep "successfully" && notify-send "Connection Established" "$success_message" && exit 0
    fi

	if [[ "$chosen_network" =~ "" ]]; then
		wifi_password=$(rofi -dmenu -password -theme-str '@import "~/.config/rofi/themes/apps.rasi"' -p "Password: " )
	fi
		nmcli device wifi connect "$chosen_id" password "$wifi_password" | grep "successfully" && notify-send "Connection Established" "$success_message"
	
fi
