#!/bin/bash
wifi=$(ls /sys/class/net | grep wl >/dev/null && echo "Wifi\n")
chosen=$(printf "Apps\nGames\n${wifi}Screenshot\nPowermenu\nSettings" | rofi -dmenu -i -theme-str '@import "~/.config/rofi/themes/apps.rasi"' -p "run")

#steam installation paths
flatpak="$HOME/.var/app/com.valvesoftware.Steam"
normal="$HOME"


steam_install=normal


runsteam () {
    #games=$(grep -n "name" "${!steam_install}"/.local/share/Steam/steamapps/*.acf | sed -e 's/^.*_//;s/\.acf:.:/ /;s/name//;s/"//g;s/\t//g;s/ /-/' | awk -F"-" '{printf "%-40s %s\n", $2, $1}' | sort | grep -vi 'proton\|steam')
    games=$(grep -h name ${!steam_install}/.local/share/Steam/steamapps/*.acf | nl)
    ids=$(grep -h appid ${!steam_install}/.local/share/Steam/steamapps/*.acf | nl)
    
    game_names=$(printf "$games" | awk '{$1="";$2="";print}' | rev | cut -c2- | rev | cut -c4-)
    echo $games

    #game_names=$(printf "$games" | awk '{$NF=""}1')
    echo $games
    rofi=$(printf "Launch Steam\n$game_names")
    chosen_game=$(printf "$rofi" | rofi -dmenu -i -theme-str '@import "~/.config/rofi/themes/apps.rasi"' -p "run" || echo no game found)
    #echo $chosen_game
    echo $chosen_game | grep "no game found" > /dev/null && exit 1
    if [[ "$chosen_game" == *"Launch Steam"* ]]; then
        [[ $steam_install == normal ]] && steam
        [[ $steam_install == flatpak ]] && flatpak run com.valvesoftware.Steam
        exit
    fi
    #echo $chosen_game | grep "launch steam" > /dev/null && [[ $steam_install == normal ]] && steam || [[ $steam_install == flatpak ]] && flatpak run com.valvesoftware.Steam
    index=$(printf "$games" | grep "$chosen_game" | awk '{print $1} ')
    id=$(printf "$ids" | grep "^     $index" | awk '{$1="";$2="";print}' | rev | cut -c2- | rev | cut -c4-)
    echo $id $index
    xdg-open steam://rungameid/$id
}

runlutris () {
    games=$(lutris -lo 2>/dev/null)
    game_names=$(printf "$games" | cut -d \| -f2)
    rofi=$(printf "Launch Lutris\n$game_names")
    chosen_game=$(printf "$rofi" | rofi -dmenu -i -theme-str '@import "~/.config/rofi/themes/apps.rasi"' -p "run" || echo no game found)
    echo $chosen_game | grep "no game found" > /dev/null && exit 1
    echo $chosen_game | grep "Launch Lutris" > /dev/null && lutris && exit 0
    id=$(printf "$games" | grep "$chosen_game" | awk '{print $1}')
    lutris lutris:rungameid/$id
}

rungames () {
    chosen=$(printf "Steam\nLutris" | rofi -dmenu -i -theme-str '@import "~/.config/rofi/themes/apps.rasi"' -p "run")
    case $chosen in
        Steam) runsteam ;;
        Lutris) runlutris ;;
        *) exit 1 ;;
    esac
}

kblayout () {
    #all_kb_maps="localectl --no-pager list-x11-keymap-layouts"
    all_kb_maps='cat /usr/share/X11/xkb/rules/evdev.lst | sed '\''/! layout/,/^$/!d;'\'' | sed 1d | head -n -2'
    echo "$($all_kb_maps)"
    chosen=$(printf $all_kb_maps | rofi -dmenu -i -theme-str '@import "~/.config/rofi/themes/apps.rasi"' -p "run")
    printf $chosen
    $all_kb_maps | grep -w $chosen &>/dev/null && ~/.config/rofi/scripts/rofi-prompt --query "Switch to the $chosen keyboard layout?" && setxkbmap $chosen
}

settings () {
    chosen=$(printf "Wallpaper\nKeyboard Layout" | rofi -dmenu -i -theme-str '@import "~/.config/rofi/themes/apps.rasi"' -p "run")
    case $chosen in
        Wallpaper) nitrogen ;;
        "Keyboard Layout") kblayout ;;
        *) exit 1 ;;
    esac
}

case $chosen in
    Games) rungames ;;
    Apps) ~/.config/rofi/scripts/rofi-apps ;;
    Wifi) ~/.config/rofi/scripts/rofi-wifi-menu ;;
    Screenshot) ~/.config/rofi/scripts/rofi-screenshot ;;
    Powermenu) ~/.config/rofi/scripts/rofi-power ;;
    Settings) settings ;;
    *) exit 1 ;;
esac
