#!/bin/bash
wifi=$(ls /sys/class/net | grep wl >/dev/null && echo "Wifi\n")
chosen=$(printf "Apps\nGames\n${wifi}Screenshot\nPowermenu" | rofi -dmenu -i -theme-str '@import "~/.config/rofi/themes/apps.rasi"' -p "run")

#steam installation paths
flatpak="$HOME/.var/app/com.valvesoftware.Steam"
normal="$HOME"


steam_install=flatpak


runsteam () {
    games=$(grep -n "name" "${!steam_install}"/.local/share/Steam/steamapps/*.acf | sed -e 's/^.*_//;s/\.acf:.:/ /;s/name//;s/"//g;s/\t//g;s/ /-/' | awk -F"-" '{printf "%-40s %s\n", $2, $1}' | sort | grep -vi 'proton\|steam')
    game_names=$(printf "$games" | awk '{$NF=""}1')
    rofi=$(printf "Launch Steam\n$game_names")
    chosen_game=$(printf "$rofi" | rofi -dmenu -i -theme-str '@import "~/.config/rofi/themes/apps.rasi"' -p "run" || echo no game found)
    #echo $chosen_game
    echo $chosen_game | grep "no game found" > /dev/null && exit 1
    if [[ "$chosen_game" == *"Launch Steam"* ]]; then
        [[ $steam_install == normal ]] && steam
        [[ $steam_install == flatpak ]] && flatpak run com.valvesoftware.Steam
        exit
    fi
    #echo $chosen_game | grep "launch steam" > /dev/null && [[ $steam_install == normal ]] && steam || [[ $steam_install == flatpak ]] && flatpak run com.valvesoftware.Steam
    id=$(printf "$games" | grep "$chosen_game" | awk '{print $NF}')
    xdg-open steam://rungameid/$id
}

runlutris () {
    games=$(lutris -lo 2>/dev/null)
    game_names=$(printf "$games" | cut -d \| -f2)
    rofi=$(printf "Launch Lutris\n$game_names")
    chosen_game=$(printf "$rofi" | rofi -dmenu -i -theme-str '@import "~/.config/rofi/themes/apps.rasi"' -p "run" || echo no game found)
    echo $chosen_game | grep "no game found" > /dev/null && exit 1
    echo $chosen_game | grep "Launch Lutris" > /dev/null && lutris && exit 0
    id=$(printf "$games" | grep "$chosen_game" | awk '{print $1}')
    lutris lutris:rungameid/$id
}

rungames () {
    chosen=$(printf "Steam\nLutris" | rofi -dmenu -i -theme-str '@import "~/.config/rofi/themes/apps.rasi"' -p "run")
    case $chosen in
        Steam) runsteam ;;
        Lutris) runlutris ;;
        *) exit 1 ;;
    esac
}

case $chosen in
    Games) rungames ;;
    Apps) ~/.config/rofi/scripts/rofi-apps ;;
    Wifi) ~/.config/rofi/scripts/rofi-wifi-menu ;;
    Screenshot) ~/.config/rofi/scripts/rofi-screenshot ;;
    Powermenu) ~/.config/rofi/scripts/rofi-power ;;
    *) exit 1 ;;
esac
